### ISSUE TITLE
How do you split the address

### ISSUE THREAD

**Issue by DarrenBelow** [brandonjbegle/nova4-google-autocomplete-field#2]
I'm looking to get it to autocomplete the address then store city in a city field, state in state field and postcode in postcode field. Is this possible with this? I assume it's the AddressMetadata?

I'm using this AddressMetadata::make('City')->fromValue('administrative_area_level_1') but it's coming back blank

**Comment by brandonjbegle** [comment]
The way you are doing it looks correct.

<img width="287" alt="Screenshot 2024-02-29 at 3 11 15 PM" src="https://github.com/brandonjbegle/nova4-google-autocomplete-field/assets/22717872/d0326eb5-f699-43ce-a832-7dee2e5a223e">

**Comment by brandonjbegle** [comment]
If you provide the actual address you are searching, I will confirm there is a result for administrative area level 1
